# -*- coding: utf-8 -*-
"""Chapter 4 Figures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13lMxQxAuzS_x28QtSW3uRjlhAuRUqo6J
"""

#Figure 1

import matplotlib.pyplot as plt

# Time points and their positions
time_points = ['I(t₀)', 'I(t₁)', 'I(t₂)', 'I(t₃)', 'I(t₄)', 'I(tₙ)', 'G(tₙ₊₁)', 'G(tₙ₊₂)', 'G(tₙ₊₃)']
positions = list(range(len(time_points)))

# Create the figure and axis
fig, ax = plt.subplots(figsize=(12, 4))

# Draw the timeline excluding dotted section
# Solid part from t0 to t4
ax.hlines(0, positions[0], positions[4], color='black')
# Dotted part between t4 and tn
ax.hlines(0, positions[4], positions[5], color='black', linestyles='dotted')
# Solid part from tn to end
ax.hlines(0, positions[5], positions[-1], color='black')

# Draw vertical ticks and labels
for pos, label in zip(positions, time_points):
    ax.vlines(pos, -0.2, 0.2, color='black')
    ax.text(pos, -0.3, label, ha='center', va='top', fontsize=12, fontweight='bold')

# Arrow pointing to SDE between I(t1) and I(t2)
arrow_x = (positions[1] + positions[2]) / 2
ax.annotate(r'$dH_t = (\mu(t) - \gamma)H_t dt + \sigma(t)H_t dW_t$',
            xy=(arrow_x, 0.2),
            xytext=(arrow_x - 0.5, 0.5),
            arrowprops=dict(facecolor='black', shrink=0.05, width=1.5, headwidth=8),
            fontsize=14, ha='center')

# Withdrawal phase arrow
ax.annotate('Withdrawal phase',
            xy=(positions[6], -0.5),
            xytext=(positions[5] + 0.3, -0.9),
            arrowprops=dict(arrowstyle='<->'),
            fontsize=12)

# Final formatting
ax.axis('off')
plt.tight_layout()
plt.show()