# -*- coding: utf-8 -*-
"""Chapter 3 Figures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fp_N2pNmYp_r3f4gn_P5765FvSxpdS2a
"""

#Figure 1

!apt-get install -y graphviz
!pip install graphviz

import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(11, 3.5))

# Time intervals
a = 1
times = [0, a, 2*a, 3*a, 4*a]
ka = 5*a
kap1 = 6*a

# Draw the solid timeline from t=0 to t=4a
ax.plot([0, 4*a], [0, 0], 'k-', lw=1.5)

# Dashed continuation from t=4a to t=(k+1)a
ax.plot([4*a, kap1], [0, 0], 'k--', lw=1.5)

# Tick marks and labels for 0 to 4a
for t in times:
    ax.plot([t, t], [-0.15, 0.15], color='black', lw=1.5)
    ax.text(t, -0.35, f't={int(t/a)}a' if t > 0 else 't=0', ha='center', fontsize=11)

# Tick marks and labels at ka and (k+1)a
ax.plot([ka, ka], [-0.15, 0.15], color='black', lw=1.5)
ax.text(ka, -0.35, r'$t=ka$', ha='center', fontsize=11)

ax.plot([kap1, kap1], [-0.15, 0.15], color='black', lw=1.5)
ax.text(kap1, -0.35, r'$t=(k+1)a$', ha='center', fontsize=11)

# Downward arrow pointing to H_{ka}
ax.annotate(r'$H_{ka}$', xy=(ka, -0.75), xytext=(ka, -2),
            arrowprops=dict(facecolor='black', arrowstyle='<-'),
            fontsize=13, color='navy', ha='center')

# Upward arrow pointing to the SDE (originating between ka and (k+1)a)
arrow_x = (ka + kap1) / 2
ax.annotate('', xy=(arrow_x, 0.85), xytext=(arrow_x, 0.15),
            arrowprops=dict(facecolor='black', arrowstyle='->'))

# SDE Equation at top right
ax.text(kap1 - 0.8, 1.5,
        r'$dH_t = (\mu - \gamma)S_t\,dt + \sigma S_t\,dW_t,$' '\n' r'$\forall t: ak < t < a(k+1)$',
        fontsize=14, va='center', ha='left', color='black')

# Formatting
ax.set_xlim(-0.5, kap1 + 3)
ax.set_ylim(-1, 1.2)
ax.axis('off')
plt.tight_layout()
plt.show()